type: google.api.Service
config_version: 3

http:
  rules:
    # Rules for WasmVerifier service
    - selector: blockscout.fluentVerifier.v1.WasmVerifier.VerifyWasm
      post: /api/v1/fluent/verify-wasm # HTTP POST endpoint for wasm verification
      body: "*" # Indicates that the entire request body is mapped to the gRPC request message

    - selector: blockscout.fluentVerifier.v1.WasmVerifier.ListAvailableVersions
      get: /api/v1/fluent/available-versions # HTTP GET endpoint for available SDK versions

    # Rules for Health service
    - selector: blockscout.fluentVerifier.v1.Health.Check
      get: /health