[package]
name = "fluent-verifier-logic"
version = "0.1.0"
edition = "2021"


[dependencies]
fluent-verifier-proto = { path = "../fluent-verifier-proto" }
anyhow = "1.0"
blockscout-display-bytes = "1.0"
tracing = "0.1"
bollard = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
semver = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "process"] }
tokio-test = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }
tonic = { workspace = true }
zip = { workspace = true }
rwasm = { version = "0.4.3", default-features = false }
reqwest = { version = "0.12.24", features = ["rustls-tls", "json"] }
hex = "0.4.3"
gix = { workspace = true }
cargo_metadata = "0.23.1"
