[package]
name = "fluent-verifier-logic"
version = "0.1.0"
edition = "2021"


[dependencies]
fluent-verifier-proto = { path = "../fluent-verifier-proto" }
anyhow = "1.0"
blockscout-display-bytes = "1.0"
tracing = "0.1"
bollard = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
semver = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
git2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "process"] }
tokio-test = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }
tonic = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
blockscout-service-launcher = { version = "0.9.0" }
pretty_assertions = "1.3"

